# SPDX-License-Identifier: GPL-2.0-only
# Amlogic amfc drivers

MODULE_NAME1 = amlogic-soc-amfc
$(MODULE_NAME1)-$(CONFIG_AMLOGIC_AMFC) = amfc.o
obj-$(CONFIG_AMLOGIC_AMFC) = $(MODULE_NAME1).o

obj-$(CONFIG_AMLOGIC_EROFS) += aml_erofs/
