obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+=	common/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+=	frame_provider/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+=	frame_sink/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+=	stream_input/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+=	framerate_adapter/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+=	media_sync/
obj-$(CONFIG_AMLOGIC_MEDIA_V4L_DEC)	+=	amvdec_ports/
