# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/DPTX_IP/dptx_IP_interface.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/DPTX_IP/dptx_IP_triliner_DP12.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/DPTX_IP/dptx_IP_DP14.o
