/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __S6_H
#define __S6_H

#define ANACTRL_FIXPLL_CTRL1                       (0x0011  << 2)
#define ANACTRL_GP0PLL_CTRL0                       (0x0020  << 2)
#define ANACTRL_GP0PLL_CTRL1                       (0x0021  << 2)
#define ANACTRL_GP0PLL_CTRL2                       (0x0022  << 2)
#define ANACTRL_GP0PLL_CTRL3                       (0x0023  << 2)
#define ANACTRL_GP0PLL_CTRL4                       (0x0024  << 2)
#define ANACTRL_HIFI0PLL_CTRL0                     (0x0040  << 2)
#define ANACTRL_HIFI0PLL_CTRL1                     (0x0041  << 2)
#define ANACTRL_HIFI0PLL_CTRL2                     (0x0042  << 2)
#define ANACTRL_HIFI0PLL_CTRL3                     (0x0043  << 2)
#define ANACTRL_HIFI0PLL_CTRL4                     (0x0044  << 2)
#define ANACTRL_HIFI1PLL_CTRL0                     (0x0045  << 2)
#define ANACTRL_HIFI1PLL_CTRL1                     (0x0046  << 2)
#define ANACTRL_HIFI1PLL_CTRL2                     (0x0047  << 2)
#define ANACTRL_HIFI1PLL_CTRL3                     (0x0048  << 2)
#define ANACTRL_HIFI1PLL_CTRL4                     (0x0049  << 2)
#define ANACTRL_CSIPLL_CTRL0                       (0x0098  << 2)
#define ANACTRL_CSIPLL_CTRL1                       (0x0099  << 2)
#define ANACTRL_CSIPLL_CTRL2                       (0x009a  << 2)
#define ANACTRL_CSIPLL_CTRL3                       (0x009b  << 2)

#define CLKCTRL_RTC_BY_OSCIN_CTRL0                 (0x0002  << 2)
#define CLKCTRL_RTC_BY_OSCIN_CTRL1                 (0x0003  << 2)
#define CLKCTRL_RTC_CTRL                           (0x0004  << 2)
#define CLKCTRL_SYS_CLK_EN0_REG0                   (0x0011  << 2)
#define CLKCTRL_SYS_CLK_EN0_REG1                   (0x0012  << 2)
#define CLKCTRL_SYS_CLK_EN0_REG2                   (0x0013  << 2)
#define CLKCTRL_SYS_CLK_EN0_REG3                   (0x0014  << 2)
#define CLKCTRL_CECB_CTRL0                         (0x0024  << 2)
#define CLKCTRL_CECB_CTRL1                         (0x0025  << 2)
#define CLKCTRL_SC_CLK_CTRL                        (0x0026  << 2)
#define CLKCTRL_DSPA_CLK_CTRL0                     (0x0027  << 2)
#define CLKCTRL_CLK12_24_CTRL                      (0x002a  << 2)
#define CLKCTRL_AXI_CLK_EN0                        (0x002b  << 2)
#define CLKCTRL_VID_CLK_CTRL                       (0x0030  << 2)
#define CLKCTRL_VID_CLK_CTRL2                      (0x0031  << 2)
#define CLKCTRL_VID_CLK_DIV                        (0x0032  << 2)
#define CLKCTRL_VIID_CLK_DIV                       (0x0033  << 2)
#define CLKCTRL_VIID_CLK_CTRL                      (0x0034  << 2)
#define CLKCTRL_HDMI_CLK_CTRL                      (0x0038  << 2)
#define CLKCTRL_VPU_CLK_CTRL                       (0x003a  << 2)
#define CLKCTRL_VPU_CLKB_CTRL                      (0x003b  << 2)
#define CLKCTRL_VPU_CLKC_CTRL                      (0x003c  << 2)
#define CLKCTRL_VID_LOCK_CLK_CTRL                  (0x003d  << 2)
#define CLKCTRL_VDIN_MEAS_CLK_CTRL                 (0x003e  << 2)
#define CLKCTRL_VAPBCLK_CTRL                       (0x003f  << 2)
#define CLKCTRL_CDAC_CLK_CTRL                      (0x0042  << 2)
#define CLKCTRL_MIPI_CSI_PHY_CLK_CTRL              (0x0043  << 2)
#define CLKCTRL_CSI2_ADAPT_CLK_CTRL                (0x0044  << 2)
#define CLKCTRL_HTX_CLK_CTRL0                      (0x0047  << 2)
#define CLKCTRL_HTX_CLK_CTRL1                      (0x0048  << 2)
#define CLKCTRL_VDEC_CLK_CTRL                      (0x0050  << 2)
#define CLKCTRL_VDEC2_CLK_CTRL                     (0x0051  << 2)
#define CLKCTRL_VDEC3_CLK_CTRL                     (0x0052  << 2)
#define CLKCTRL_VDEC4_CLK_CTRL                     (0x0053  << 2)
#define CLKCTRL_TS_CLK_CTRL                        (0x0056  << 2)
#define CLKCTRL_MALI_CLK_CTRL                      (0x0057  << 2)
#define CLKCTRL_MALI_STACK_CLK_CTRL                (0x0058  << 2)
#define CLKCTRL_ETH_CLK_CTRL                       (0x0059  << 2)
#define CLKCTRL_NAND_CLK_CTRL                      (0x005a  << 2)
#define CLKCTRL_SD_EMMC_CLK_CTRL                   (0x005b  << 2)
#define CLKCTRL_SPICC_CLK_CTRL                     (0x005d  << 2)
#define CLKCTRL_GEN_CLK_CTRL                       (0x005e  << 2)
#define CLKCTRL_SAR_CLK_CTRL0                      (0x005f  << 2)
#define CLKCTRL_PWM_CLK_AB_CTRL                    (0x0060  << 2)
#define CLKCTRL_PWM_CLK_GH_CTRL                    (0x0063  << 2)
#define CLKCTRL_PWM_CLK_IJ_CTRL                    (0x0064  << 2)
#define CLKCTRL_AMFC_CLK_CTRL                      (0x0065  << 2)
#define CLKCTRL_VC9000E_CLK_CTRL                   (0x0066  << 2)
#define CLKCTRL_NNA_CLK_CTRL                       (0x0067  << 2)
#define CLKCTRL_USB_CLK_CTRL                       (0x0068  << 2)
#define CLKCTRL_PCIE_CLK_CTRL                      (0x0069  << 2)
#define CLKCTRL_CMPR_CLK_CTRL                      (0x006a  << 2)
#define CLKCTRL_DEWARPA_CLK_CTRL                   (0x006b  << 2)

#endif  /* __S6_H */
