/* SPDX-License-Identifier: GPL-2.0+ */
/*
 *
 * Copyright (C) 2019 Amlogic, Inc. All rights reserved.
 *
 */

#ifndef __AML_LCD_DEBUG_H__
#define __AML_LCD_DEBUG_H__
#include <linux/amlogic/media/vout/DisplayPort/DPTX.h>
#include <linux/amlogic/media/vout/DisplayPort/DPCD_REG.h>
#include "dptx_reg_op.h"
#include "DPTX_IP/dptx_IP_REG_T7.h"

#define DPTX_REG_END        0xffffffff
struct reg_sets_s {
	char *name;
	u32 addr;
};

enum dptx_reg_types_e {
	DPTX_REG_TYPE_VENC,
	DPTX_REG_TYPE_VENC_IF,
	DPTX_REG_TYPE_VENC_DATA,
	DPTX_REG_TYPE_PLL,
	DPTX_REG_TYPE_PHY,
	DPTX_REG_TYPE_CLK,
	DPTX_REG_TYPE_DP_IP,
	DPTX_REG_TYPE_COMBO_DPHY,
	DPTX_REG_TYPE_VPU,
	DPTX_REG_TYPE_DPCD_RECEIVER_CAP,
	DPTX_REG_TYPE_DPCD_LINK_CONFIG,
	DPTX_REG_TYPE_DPCD_LINK_STATUS,
};

static char *dptx_reg_type_name[] = {
	"VENC", "VENC IF", "VENC DATA", "PLL", "PHY", "CLK", "DPTX-IP", "COMBO_DPHY", "VPU",
	"DPCD-Receiver Capability", "DPCD-Link Configuration", "DPCD-Link/Sink Status",
};

struct dptx_debug_info_reg_s {
	struct reg_sets_s *reg_pll;
	struct reg_sets_s *reg_clk;
	struct reg_sets_s *reg_combo_dphy;
	struct reg_sets_s *reg_encl;
	struct reg_sets_s *reg_encl_if;
	struct reg_sets_s *reg_encl_data;
	struct reg_sets_s *reg_vpu;
	struct reg_sets_s *reg_analog_phy;
	struct reg_sets_s *reg_dptx_IP;
};

static struct reg_sets_s dptx_regs_pll_t7_0[] = {
	{"PLL0_CNTL0", ANACTRL_TCON_PLL0_CNTL0},
	{"PLL0_CNTL1", ANACTRL_TCON_PLL0_CNTL1},
	{"PLL0_CNTL2", ANACTRL_TCON_PLL0_CNTL2},
	{"PLL0_CNTL3", ANACTRL_TCON_PLL0_CNTL3},
	{"PLL0_CNTL4", ANACTRL_TCON_PLL0_CNTL4},
	{"PLL0_STS",   ANACTRL_TCON_PLL0_STS},
	{"",           DPTX_REG_END},
};

static struct reg_sets_s dptx_regs_pll_t7_1[] = {
	{"PLL1_CNTL0", ANACTRL_TCON_PLL1_CNTL0},
	{"PLL1_CNTL1", ANACTRL_TCON_PLL1_CNTL1},
	{"PLL1_CNTL2", ANACTRL_TCON_PLL1_CNTL2},
	{"PLL1_CNTL3", ANACTRL_TCON_PLL1_CNTL3},
	{"PLL1_CNTL4", ANACTRL_TCON_PLL1_CNTL4},
	{"PLL1_STS",   ANACTRL_TCON_PLL1_STS},
	{"",           DPTX_REG_END},
};

static struct reg_sets_s dptx_regs_clk_t7_0[] = {
	{"VIID_CLK0_DIV",  CLKCTRL_VIID_CLK0_DIV},
	{"VIID_CLK0_CTRL", CLKCTRL_VIID_CLK0_CTRL},
	{"VID_CLK0_CTRL2", CLKCTRL_VID_CLK0_CTRL2},
	{"",               DPTX_REG_END},
};

static struct reg_sets_s dptx_regs_clk_t7_1[] = {
	{"VIID_CLK1_DIV",  CLKCTRL_VIID_CLK1_DIV},
	{"VIID_CLK1_CTRL", CLKCTRL_VIID_CLK1_CTRL},
	{"VID_CLK1_CTRL2", CLKCTRL_VID_CLK1_CTRL2},
	{"",               DPTX_REG_END},
};

static struct reg_sets_s dptx_regs_combo_dphy_t7_0[] = {
	{"VID_PLL0_DIV",           COMBO_DPHY_VID_PLL0_DIV},
	{"COMBO_DPHY_CNTL0",       COMBO_DPHY_CNTL0},
	{"COMBO_DPHY_CNTL1",       COMBO_DPHY_CNTL1},
	{"EDP_LVDS_TX_PHY0_CNTL0", COMBO_DPHY_EDP_LVDS_TX_PHY0_CNTL0},
	{"EDP_LVDS_TX_PHY0_CNTL1", COMBO_DPHY_EDP_LVDS_TX_PHY0_CNTL1},
	{"",                       DPTX_REG_END},
};

static struct reg_sets_s dptx_regs_combo_dphy_t7_1[] = {
	{"VID_PLL1_DIV",           COMBO_DPHY_VID_PLL1_DIV},
	{"COMBO_DPHY_CNTL0",       COMBO_DPHY_CNTL0},
	{"COMBO_DPHY_CNTL1",       COMBO_DPHY_CNTL1},
	{"EDP_LVDS_TX_PHY1_CNTL0", COMBO_DPHY_EDP_LVDS_TX_PHY1_CNTL0},
	{"EDP_LVDS_TX_PHY1_CNTL1", COMBO_DPHY_EDP_LVDS_TX_PHY1_CNTL1},
	{"",                       DPTX_REG_END},
};

static struct reg_sets_s dptx_regs_analog_phy_t7[] = {
	{"PHY_CNTL1",  ANACTRL_DIF_PHY_CNTL1},
	{"PHY_CNTL2",  ANACTRL_DIF_PHY_CNTL2},
	{"PHY_CNTL3",  ANACTRL_DIF_PHY_CNTL3},
	{"PHY_CNTL4",  ANACTRL_DIF_PHY_CNTL4},
	{"PHY_CNTL5",  ANACTRL_DIF_PHY_CNTL5},
	{"PHY_CNTL6",  ANACTRL_DIF_PHY_CNTL6},
	{"PHY_CNTL10", ANACTRL_DIF_PHY_CNTL10},
	{"PHY_CNTL11", ANACTRL_DIF_PHY_CNTL11},
	{"PHY_CNTL12", ANACTRL_DIF_PHY_CNTL12},
	{"PHY_CNTL13", ANACTRL_DIF_PHY_CNTL13},
	{"PHY_CNTL14", ANACTRL_DIF_PHY_CNTL14},
	{"PHY_CNTL15", ANACTRL_DIF_PHY_CNTL15},
	{"PHY_CNTL19", ANACTRL_DIF_PHY_CNTL19},
	{"PHY_CNTL20", ANACTRL_DIF_PHY_CNTL20},
	{"PHY_CNTL21", ANACTRL_DIF_PHY_CNTL21},
	{"",           DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_vpu_t7[] = {
	{"VPU_VIU_VENC_MUX_CTRL", VPU_VIU_VENC_MUX_CTRL},
	{"VPU_DISP_VIU0_CTRL",    VPU_DISP_VIU0_CTRL},
	{"VPU_DISP_VIU1_CTRL",    VPU_DISP_VIU1_CTRL},
	{"VPU_DISP_VIU2_CTRL",    VPU_DISP_VIU2_CTRL},
	{"",                      DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_venc_if_t7[] = {
	{"", DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_venc_data_t7[] = {
	{"LCD_GAMMA_CNTL_PORT0", LCD_GAMMA_CNTL_PORT0},
	{"LCD_RGB_BASE_ADDR",    LCD_RGB_BASE_ADDR},
	{"LCD_RGB_COEFF_ADDR",   LCD_RGB_COEFF_ADDR},
	{"LCD_POL_CNTL_ADDR",    LCD_POL_CNTL_ADDR},
	{"LCD_DITH_CNTL_ADDR",   LCD_DITH_CNTL_ADDR},
	{"",                     DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_venc_t7[] = {
	{"ENCL_VIDEO_EN",          ENCL_VIDEO_EN},
	{"ENCL_VIDEO_MODE",        ENCL_VIDEO_MODE},
	{"ENCL_VIDEO_MODE_ADV",    ENCL_VIDEO_MODE_ADV},
	{"ENCL_VIDEO_MAX_PXCNT",   ENCL_VIDEO_MAX_PXCNT},
	{"ENCL_VIDEO_MAX_LNCNT",   ENCL_VIDEO_MAX_LNCNT},
	{"ENCL_VIDEO_HAVON_BEGIN", ENCL_VIDEO_HAVON_BEGIN},
	{"ENCL_VIDEO_HAVON_END",   ENCL_VIDEO_HAVON_END},
	{"ENCL_VIDEO_VAVON_BLINE", ENCL_VIDEO_VAVON_BLINE},
	{"ENCL_VIDEO_VAVON_ELINE", ENCL_VIDEO_VAVON_ELINE},
	{"ENCL_VIDEO_HSO_BEGIN",   ENCL_VIDEO_HSO_BEGIN},
	{"ENCL_VIDEO_HSO_END",     ENCL_VIDEO_HSO_END},
	{"ENCL_VIDEO_VSO_BEGIN",   ENCL_VIDEO_VSO_BEGIN},
	{"ENCL_VIDEO_VSO_END",     ENCL_VIDEO_VSO_END},
	{"ENCL_VIDEO_VSO_BLINE",   ENCL_VIDEO_VSO_BLINE},
	{"ENCL_VIDEO_VSO_ELINE",   ENCL_VIDEO_VSO_ELINE},
	{"ENCL_VIDEO_RGBIN_CTRL",  ENCL_VIDEO_RGBIN_CTRL},
	{"ENCL_INBUF_CNTL0",       ENCL_INBUF_CNTL0},
	{"ENCL_INBUF_CNTL1",       ENCL_INBUF_CNTL1},
	{"VPU_VENC_CTRL",          VPU_VENC_CTRL},
	{"",                       DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_dptx_IP[] = {
	{"LINK_BW_SET",               EDP_TX_LINK_BW_SET},
	{"LINK_COUNT_SET",            EDP_TX_LINK_COUNT_SET},
	{"TRAINING_PATTERN_SET",      EDP_TX_TRAINING_PATTERN_SET},
	{"SCRAMBLING_DISABLE",        EDP_TX_SCRAMBLING_DISABLE},
	{"TRANSMITTER_OUTPUT_ENABLE", EDP_TX_TRANSMITTER_OUTPUT_ENABLE},
	{"AUX_INTERRUPT_MASK",        EDP_TX_AUX_INTERRUPT_MASK},
	{"MAIN_STREAM_ENABLE",        EDP_TX_MAIN_STREAM_ENABLE},
	{"PHY_RESET",                 EDP_TX_PHY_RESET},
	{"PHY_STATUS",                EDP_TX_PHY_STATUS},
	{"AUX_COMMAND",               EDP_TX_AUX_COMMAND},
	{"AUX_ADDRESS",               EDP_TX_AUX_ADDRESS},
	{"AUX_STATE",                 EDP_TX_AUX_STATE},
	{"AUX_REPLY_CODE",            EDP_TX_AUX_REPLY_CODE},
	{"AUX_REPLY_COUNT",           EDP_TX_AUX_REPLY_COUNT},
	{"AUX_REPLY_DATA_COUNT",      EDP_TX_AUX_REPLY_DATA_COUNT},
	{"AUX_TRANSFER_STATUS",       EDP_TX_AUX_TRANSFER_STATUS},
	{"",                          DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_DPCD_receiver_cap[] = {
	{"DPCD_REV",                    DPCD_DPCD_REV},
	{"MAX_LINK_RATE",               DPCD_MAX_LINK_RATE},
	{"MAX_LANE_COUNT",              DPCD_MAX_LANE_COUNT},
	{"MAX_DOWNSPREAD",              DPCD_MAX_DOWNSPREAD},
	{"NORP",                        DPCD_NORP},
	{"DOWNSTREAMPORT_PRESENT",      DPCD_DOWNSTREAMPORT_PRESENT},
	{"MAIN_LINK_CHANNEL_CODING",    DPCD_MAIN_LINK_CHANNEL_CODING},
	{"NUM_DOWNSTREAM_PORTS",        DPCD_NUM_DOWNSTREAM_PORTS},
	{"RECEIVE_PORT0_CAP_0",         DPCD_RECEIVE_PORT0_CAP_0},
	{"RECEIVE_PORT0_CAP_1",         DPCD_RECEIVE_PORT0_CAP_1},
	{"RECEIVE_PORT1_CAP_0",         DPCD_RECEIVE_PORT1_CAP_0},
	{"RECEIVE_PORT1_CAP_1",         DPCD_RECEIVE_PORT1_CAP_1},
	{"I2C_SPEED_CAP",               DPCD_I2C_SPEED_CAP},
	{"eDP_CONFIGURATION_CAP",       DPCD_eDP_CONFIGURATION_CAP},
	{"TRAINING_AUX_RD_INTERVAL",    DPCD_TRAINING_AUX_RD_INTERVAL},
	{"FAUX_CAP",                    DPCD_FAUX_CAP},
	{"MSTM_CAP",                    DPCD_MSTM_CAP},
	{"NUMBER_OF_AUDIO_ENDPOINTS",   DPCD_NUMBER_OF_AUDIO_ENDPOINTS},
	{"PSR_SUPPORT",                 DPCD_PSR_SUPPORT},
	{"PSR_CAPS",                    DPCD_PSR_CAPS},
	{"DETAILED_CAP_INFO_AVAILABLE", DPCD_DETAILED_CAP_INFO_AVAILABLE},
	{"",                            DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_DPCD_link_config[] = {
	{"LINK_BW_SET",                      DPCD_LINK_BW_SET},
	{"LANE_COUNT_SET",                   DPCD_LANE_COUNT_SET},
	{"TRAINING_PATTERN_SET",             DPCD_TRAINING_PATTERN_SET},
	{"TRAINING_LANE0_SET",               DPCD_TRAINING_LANE0_SET},
	{"TRAINING_LANE1_SET",               DPCD_TRAINING_LANE1_SET},
	{"TRAINING_LANE2_SET",               DPCD_TRAINING_LANE2_SET},
	{"TRAINING_LANE3_SET",               DPCD_TRAINING_LANE3_SET},
	{"DOWNSPREAD_CONTROL",               DPCD_DOWNSPREAD_CONTROL},
	{"MAIN_LINK_CODING_SET",             DPCD_MAIN_LINK_CODING_SET},
	{"I2C_SPEED_CONTROL_STATUS_BIT_MAP", DPCD_I2C_SPEED_CONTROL_STATUS_BIT_MAP},
	{"eDP_CONFIGURATION_SET",            DPCD_eDP_CONFIGURATION_SET},
	{"LINK_QUAL_LANE0_SET",              DPCD_LINK_QUAL_LANE0_SET},
	{"LINK_QUAL_LANE1_SET",              DPCD_LINK_QUAL_LANE1_SET},
	{"LINK_QUAL_LANE2_SET",              DPCD_LINK_QUAL_LANE2_SET},
	{"LINK_QUAL_LANE3_SET",              DPCD_LINK_QUAL_LANE3_SET},
	{"TRAINING_LANE0_1_SET2",            DPCD_TRAINING_LANE0_1_SET2},
	{"TRAINING_LANE2_3_SET2",            DPCD_TRAINING_LANE2_3_SET2},
	{"",                                 DPTX_REG_END},
};

static struct reg_sets_s dptx_reg_DPCD_link_status[] = {
	{"SINK_COUNT",                 DPCD_SINK_COUNT},
	{"DEVICE_SERVICE_IRQ_VECTOR",  DPCD_DEVICE_SERVICE_IRQ_VECTOR},
	{"LANE0_1_STATUS",             DPCD_LANE0_1_STATUS},
	{"LANE2_3_STATUS",             DPCD_LANE2_3_STATUS},
	{"LANE_ALIGN__STATUS_UPDATED", DPCD_LANE_ALIGN__STATUS_UPDATED},
	{"SINK_STATUS",                DPCD_SINK_STATUS},
	{"ADJUST_REQUEST_LANE0_1",     DPCD_ADJUST_REQUEST_LANE0_1},
	{"ADJUST_REQUEST_LANE2_3",     DPCD_ADJUST_REQUEST_LANE2_3},
	{"TRAINING_SCORE_LANE0",       DPCD_TRAINING_SCORE_LANE0},
	{"TRAINING_SCORE_LANE1",       DPCD_TRAINING_SCORE_LANE1},
	{"TRAINING_SCORE_LANE2",       DPCD_TRAINING_SCORE_LANE2},
	{"TRAINING_SCORE_LANE3",       DPCD_TRAINING_SCORE_LANE3},
	{"SYMBOL_ERROR_COUNT_LANE0",   DPCD_SYMBOL_ERROR_COUNT_LANE0},
	{"SYMBOL_ERROR_COUNT_LANE0",   DPCD_SYMBOL_ERROR_COUNT_LANE0_},
	{"SYMBOL_ERROR_COUNT_LANE1",   DPCD_SYMBOL_ERROR_COUNT_LANE1},
	{"SYMBOL_ERROR_COUNT_LANE1",   DPCD_SYMBOL_ERROR_COUNT_LANE1_},
	{"SYMBOL_ERROR_COUNT_LANE2",   DPCD_SYMBOL_ERROR_COUNT_LANE2},
	{"SYMBOL_ERROR_COUNT_LANE2",   DPCD_SYMBOL_ERROR_COUNT_LANE2_},
	{"SYMBOL_ERROR_COUNT_LANE3",   DPCD_SYMBOL_ERROR_COUNT_LANE3},
	{"SYMBOL_ERROR_COUNT_LANE3",   DPCD_SYMBOL_ERROR_COUNT_LANE3_},
	{"",                           DPTX_REG_END},
};

#endif
