# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_common.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_DACP.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_drm.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_notify.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_EDID_DisplayID.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_link_training.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_reg_op.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_vmode_mgr.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_vout_serve.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_vout.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_driver.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/dptx_utils.o

include $(COMMON_DRIVERS_DIR)/drivers/media/vout/DisplayPort/VENC/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vout/DisplayPort/CLK/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vout/DisplayPort/DPTX_IP/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vout/DisplayPort/PHY/Makefile
