# dtb-y += overlay.dtbo

dtb-y += dht11.dtbo \
         display_vu7c.dtbo \
         gpio_power_button.dtbo \
         hktft32.dtbo \
         i2c0.dtbo \
         i2c1.dtbo \
         i2c2.dtbo \
         ir.dtbo \
         mcp2515.dtbo \
         mcp2515_12mhz.dtbo \
         mcp2515_16mhz.dtbo \
         mcp2517fd.dtbo \
         onewire.dtbo \
         pcf8563.dtbo \
         pwm_a.dtbo \
         pwm_b.dtbo \
         pwm_c.dtbo \
         pwm_f.dtbo \
         spdif_a.dtbo \
         spi0.dtbo \
         spi0-with-hw-cs.dtbo \
         uart1.dtbo \
         uart1-with-ctsrts.dtbo \
         uart2.dtbo \
         uart3.dtbo \
         weather_board_zero.dtbo
