# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/PHY/dptx_phy_if.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DisplayPort_TX) += vout/DisplayPort/PHY/dptx_phy_t7.o
